apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::350538286616:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-S9EHP3SHQA9L
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2022-08-18T14:57:33Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1640"
  uid: e2fa5d60-a79d-4c2f-9e6c-d6d55fd03667
